### ISSUE TITLE
not getting any scripts running

### ISSUE THREAD

**Issue by gedw99** [MircoT/programmable-matter-simulator#1]
Hey this is really interesting use tengo.

I am on Mac and not getting any interactivity. Can you let me know what could be wrong..

``` 
go generate ./...
go build . 
wc -c ./programmable-matter-simulator 
 11199312 ./programmable-matter-simulator
./programmable-matter-simulator
[]
[]
[]
[]
``` 

I then press 0, 1 etc to load the different scripts but i get nothing and the terminal just shows the "[]", which seems to show its not getting loaded..

**Comment by MircoT** [comment]
Hi @gedw99, to start the simulation you have to press `Space`. With the key `H` you can see a help dialog with some useful command. I'll add these to the main README.

**Comment by MircoT** [comment]
Updated the README with the essential informations.
